# Generated by Django 5.1 on 2024-09-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='staduim',
            new_name='stadium',
        ),
    ]
