# Generated by Django 5.1 on 2025-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_event_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='on_bench',
            field=models.BooleanField(default=False),
        ),
    ]
