# Generated by Django 5.1 on 2025-01-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_lineup_on_bench'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(help_text='Wydarzenie związane z tą zmianą', on_delete=django.db.models.deletion.CASCADE, related_name='substitution', to='football.event')),
                ('player_in', models.ForeignKey(help_text='Zawodnik wchodzący na boisko', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_in', to='football.player')),
            ],
        ),
    ]
