# Generated by Django 5.1.7 on 2025-03-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_substitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
